services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - frontend-modules:/app/node_modules
    networks:
      - aula-network
    # stdin_open: true
    # tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend-modules:/app/node_modules
    networks:
      - aula-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - aula-network

networks:
  aula-network:
    driver: bridge

volumes:
  mongo-data:
    name: mongo-data
  mongo-config:
    name: mongo-config
  frontend-modules:
  backend-modules:
