services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend-modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    restart: always
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    ports: []
    volumes:
      - ./backend:/app
      - backend-modules:/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports: []
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongo-data:
    name: mongo-data
  mongo-config:
    name: mongo-config
  frontend-modules:
  backend-modules:
