services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
      - frontend-modules:/app/node_modules
    network_mode: host
    # stdin_open: true
    # tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    expose:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend-modules:/app/node_modules

  mongo:
    image: mongo:latest
    # container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

volumes:
  mongo-data:
    name: mongo-data
  mongo-config:
    name: mongo-config
  frontend-modules:
  backend-modules:
