apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/sergio-cervantes/aula/frontend:0.1
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: frontend-source
              mountPath: /app
      volumes:
        - name: frontend-source
          hostPath:
            path: /home/sergio/aula/frontend
            type: Directory
        - name: frontend-modules
          emptyDir: {}
