apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aula-ingress
spec:
  rules:
    - host: backend.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000

